ci: always install staticcheck, even on failures (#23)

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -39,6 +39,7 @@ jobs:
         if: success() || failure() # run this step even if the previous one failed
         run: go vet ./...
       - name: Install staticcheck
+        if: success() || failure() # run this step even if the previous one failed
         run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.7
       - name: staticcheck
         if: success() || failure() # run this step even if the previous one failed
